
services:
  web:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # Remove host port mapping to allow scaling
    # ports:
    #   - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"  # Host port mapping is fine for single Redis instance
    volumes:
      - redis-data:/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"   # Access load balancer on localhost:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge

  
